version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: serviceapp-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/serviceapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 17054739Ze@
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    container_name: serviceapp-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: serviceapp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 17054739Ze@
      MYSQL_DATABASE: serviceapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
